### ISSUE TITLE
Feature: Promise/Async-Await behaviour in solace connection

### ISSUE THREAD

**Issue by jmpargana** [SolaceSamples/solace-samples-nodejs#39]
# Feature: Promise/Async-Await behaviour in solace connection

Hey!

My team is using this nodejs implementation of solace as a form of communication between the microservice modules in our project.

Since we need to publish to multiple topics in each module, we instantiate the connection to solace per topic only once our controllers need to publish something.

Currently the `connect` function provided by _solclientjs_ establishes the connection in the background asynchronously, but without returning a promise. We need to set a timeout function for a couple of seconds just to make sure the connection is set and we won't fail to publish the message.

Is there a way to change the behavior of the `connect` function to return a `Promise`, so we can fearlessly await its completion and publish the message?

Here is an example:

```typescript
class Publisher {
  constructor(topic: string) {
    ...
    publisher.connect()                     // ideally could be called
                                            // `await publisher.connect()`
  }
}

class Manager {
  private instances: Map<string, Publisher> = new Map()

  publishIn (topic: string, message: string) {
    let instance = this.instances.get(topic)
    if (!instance) {
      instance = new Publisher(topic)
      setTimeout(() => {}, 10000)           // We need this to make sure the connection is established
                                            // If `connect` returned a promise, we could simple await
                                            // inside the constructor
      this.instances.set(topic, instance)
    }

    instance.publish(message)
  }
}
```

**Comment by TamimiGitHub** [comment]
Hey @jmpargana ! 

To check if the connection is established with the solace broker you will have to leverage the status code `SessionEventCode#UP_NOTICE` in a callback function since this event is only emitted on successful registration of a listener with the broker. if you checkout the EventMonitor file under `src/features` (https://github.com/SolaceSamples/solace-samples-nodejs/tree/master/src/features) you will see how you can monitoring the triggering of events in a callback behaviour.

you can implement something along the lines of
```
this.instance.on(solace.SessionEventCode.UP_NOTICE, function (sessionEvent) {
            this.instances.set(topic, instance)
            this.instance.publish(message)
        });
```

This way, the implementation will be "event-driven".

One thing to note, is depending on your design, you will want to make sure you are not establishing a connection on every message you publish on a different topic. So if a module is publishing on multiple topics, it will have to start the connection to the solace broker once on init of the module. 

Also - are you aware of the solace community forum https://solace.community/? you can share more details about your use-case, interact with our community of developers and employees there as well! I would recommend signing up for an account. Hopefully this helps!

**Comment by jmpargana** [comment]
Oh, that's a good idea. Thank you for spending your time in helping us out!

**Comment by TamimiGitHub** [comment]
and btw @jmpargana we started a tip and trick discussion around this on the community if you want to check it out https://solace.community/discussion/672/listening-to-events-in-your-javascript-nodejs-application-promise-async-await-vs-callbacks/p1?new=1 other members might pitch in and share their ideas on how they have used status codes in their JS applications. Feel free to monitor it or contribute as well :)
