### ISSUE TITLE
Attaching Protobuf as Binary will Add Additional Characters

### ISSUE THREAD

**Issue by raymondsquared** [SolaceSamples/solace-samples-nodejs#41]
### **What version of solace library are you using**
protobufjs: 7.2.2
solclientjs: 10.12

### **Does this issue reproduce with the latest release?**
yes

### **What did you do?**

1. Create a solace guaranteed publisher (topic)
2. Create a solace guaranteed subscriber (durable queue), subscribe to the above topic
3. Create a .proto file
4. Create a solace message and encode your payload based on the protofile created above
5. Publish the above message with `.setBinaryAttachment()`
6. Subscribe to the above message and invoke `.getBinaryAttachment()`

### **What did you expect to see?**

When I inspect the protofile buffer & bytes, here's the correct payload should be:
```
AttachmentBuffer: <Buffer ba 89 01 03 0a 01 61>
AttachmentBytes: Uint8Array(7) [ 186, 137,  1, 3,  10, 1, 97 ]
```

### **What did you see instead?**

However, once the message is attached as binary and when I try seeing the content with `getBinaryAttachment()`, there were some additional characters injected into the data,

it seems to be adding a random character `Â` - buffer: `ca` / decimal `194` shown below when I inspect my payload and my deserialising will fail because of this.

```
AttachmentBuffer: <Buffer **ca** ba **ca** 89 01 03 0a 01 61>
AttachmentBytes: Uint8Array(9) [ **194**, 186, **194**, 137,  1, 3,  10, 1, 97 ]
```

**Comment by aaron-613** [comment]
HI @raymondsquared .  Just noticed this Issue here.  I'm not a JS person, but am wondering: did you verify with another Solace API like SdkPerf Java?  (which you can grab from our solace.com/downloads page).  Configure it to subscribe to the same topic and do `-md` for message dump to see the binary payload.

I agree that's super weird.  I've seen character encoding issues with JS between UFF-8 and UTF-16, but this is all binary so shouldn't matter.

Or did you manage to resolve this?

**Comment by Mrc0113** [comment]
Closing since there hasn't been a response in over 30 days. Can re-open if necessary.
